services:
  app:
    image: ghcr.io/thomasbdc/cdonvm:latest    # change OWNER/REPO
    env_file:
      - ./app/app.env
    restart: always
    expose:
      - "8080"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/health || curl -fsS http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:stable
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
